### ISSUE TITLE
Nothing Spawning into Gazebo

### ISSUE THREAD

**Issue by sihengt** [navalab/ARHex#5]
I was trying out your repository but I find that upon running `roslaunch arhex_gazebo arhex.launch`, nothing spawns into the Gazebo world. I have amended the launch file to include a verbose flag, but Gazebo does not complain. I have also checked the URDF generated by the `xacro` and there aren't any issues.

Any ideas?

**Comment by sihengt** [comment]
I realized my problem - there's no issue with your code. My Ubuntu's ROS distribution has stopped working with all python scripts. I manually used Gazebo's service to test the robot's URDF and it had no issues spawning a robot in.

**Comment by StanleySun233** [comment]
Hi, how you solve this issues?

**Comment by sihengt** [comment]
Mine was a silly issue - my Ubuntu ROS distributions were broken due to an automatic update. I tested that it worked with Gazebo by calling the Gazebo service to spawn robot URDF.

You'd have best luck following the README and using the launch files provided by the repository owners:

`roslaunch arhex_gazebo arhex.launch`
